spring:
  application:
    name: multi
  config:
    import: configserver:http://${CLOUD_CONFIG_SERVER:localhost}:${CLOUD_CONFIG_SERVER_PORT:8888}/
  profiles:
    active: ${SPRING_PROFILE:default}
  codec:
    max-in-memory-size: 10MB

server:
  port: 8006

management:
  metrics:
    tags:
      application: ${INSTANCE_ENVIRONMENT:LOCAL}-${spring.application.name}-${INSTANCE_ID:default}
