spring:
  application:
    name: gateway
  config:
    import: configserver:http://${CLOUD_CONFIG_SERVER:localhost}:${CLOUD_CONFIG_SERVER_PORT:8888}/
  profiles:
    active: ${SPRING_PROFILE:default}
  main:
    allow-circular-references: true

management:
  metrics:
    tags:
      application: ${INSTANCE_ENVIRONMENT:LOCAL}-${spring.application.name}-${INSTANCE_ID:default}
  endpoint:
    gateway:
      enabled: true

server:
  port: 8080
